import { prisma } from "@/lib/db";
import { LogoMark } from "@/components/Logo";
import { Check, Alert, Shield, Lock } from "@/components/icons";
import PrintButton from "@/components/PrintButton";

export const dynamic = "force-dynamic";

type Signal = { key: string; label: string; status: "ok" | "warn" | "risk"; detail: string };
const BAND_LABEL = { green: "Trusted", yellow: "Review advised", red: "High risk" } as const;

export default async function VerifiedPage({ params }: { params: Promise<{ token: string }> }) {
  const { token } = await params;
  const report = await prisma.trustReport.findFirst({ where: { shareToken: token } });

  if (!report) {
    return (
      <div className="verified-wrap">
        <div className="verified-card" style={{ textAlign: "center" }}>
          <LogoMark size={34} />
          <h1 style={{ marginTop: 14 }}>Report not found</h1>
          <p className="muted">This verification link is invalid or has been revoked.</p>
        </div>
      </div>
    );
  }

  const owner = await prisma.user.findUnique({ where: { id: report.userId }, select: { brandName: true, brandColor: true, company: true } });
  const brand = owner?.brandName || owner?.company || null;
  const accent = /^#[0-9a-fA-F]{6}$/.test(owner?.brandColor || "") ? owner!.brandColor! : null;

  const signals: Signal[] = JSON.parse(report.signals || "[]");
  const ordered = [...signals.filter(s => s.status === "risk"), ...signals.filter(s => s.status === "warn"), ...signals.filter(s => s.status === "ok")];
  const passed = signals.filter(s => s.status === "ok").length;

  return (
    <div className="verified-wrap">
      <div className="verified-card" style={accent ? { borderTop: `3px solid ${accent}` } : undefined}>
        <div className="verified-top">
          <div className="logo">
            <LogoMark size={30} />
            <span className="logo-words">{brand || "Veridity"}<small>{brand ? "verified by TrueHire" : "TrueHire Verified"}</small></span>
          </div>
          <PrintButton />
        </div>

        <div className={`verified-hero ${report.band}`}>
          <div className="vh-seal" style={accent && report.band !== "red" ? { background: accent, color: "#fff" } : undefined}>
            {report.band === "green" ? <Shield /> : report.band === "red" ? <Alert /> : <Shield />}
          </div>
          <div>
            <div className="vh-band">{BAND_LABEL[report.band as keyof typeof BAND_LABEL] || report.band}</div>
            <div className="vh-score">Trust score <b>{report.score}</b><span> / 100</span></div>
          </div>
        </div>

        <div className="verified-meta">
          {report.candidateName && <div><span className="k">Candidate</span><span className="v">{report.candidateName}</span></div>}
          <div><span className="k">Verified</span><span className="v">{new Date(report.createdAt).toLocaleDateString(undefined, { year: "numeric", month: "long", day: "numeric" })}</span></div>
          <div><span className="k">Checks passed</span><span className="v">{passed} / {signals.length}</span></div>
          <div><span className="k">Report ID</span><span className="v mono">{report.id.slice(0, 12)}</span></div>
        </div>

        <div className="trust-signals">
          {ordered.map((s) => (
            <div key={s.key} className={`trust-sig ${s.status}`}>
              <span className="ts-ic">{s.status === "ok" ? <Check /> : <Alert />}</span>
              <div><b>{s.label}</b><span>{s.detail}</span></div>
            </div>
          ))}
        </div>

        <div className="verified-foot">
          <span><Lock /> Independently generated by TrueHire — a fraud-risk signal, not an automated hiring decision.</span>
          <span>veridity.in · © Veridity</span>
        </div>
      </div>
    </div>
  );
}
